<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_FastOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
$_helper = $this->helper('Bss\FastOrder\Helper\Data');
?>
<div class="bss-swatch-opt-<?php /* @escapeNotVerified */
echo $block->getProduct()->getId() ?>"></div>
<script>
    require(["jquery", "jquery/ui", "bss/fastorder_swatch"], function ($) {
        var fastorderRow = $('.bss-row-select').val();
        $('.bss-swatch-opt-<?php /* @escapeNotVerified */ echo $block->getProduct()->getId() ?>').FastOrderSwatch({
            jsonConfig: <?php /* @escapeNotVerified */ echo $block->getJsonConfig(); ?>,
            jsonSwatchConfig: <?php /* @escapeNotVerified */ echo $block->getJsonSwatchConfig(); ?>,
            mediaCallback: '<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>',
            fastorderRow: fastorderRow,
            formatPrice: '<?php echo $_helper->getFomatPrice();?>',
        });
    });
</script>