<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * BSS Commerce does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * BSS Commerce does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   BSS
 * @package    Bss_FastOrder
 * @author     Extension Team
 * @copyright  Copyright (c) 2015-2016 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
$_product = $block->getProduct();
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$sortOrder = $block->getSortOrder();
$_helper = $this->helper('Bss\FastOrder\Helper\Data');
?>
<input type="hidden" class="bss-row-select" value="<?php echo $sortOrder; ?>">
<div class="bss-product-info">
    <img class="photo image" src="<?php echo $_helper->getProductImage($_product); ?>" width="100" height="100">
    <div class="product-name">
        <strong class="product name"><?php echo $_product->getName(); ?></strong>
    </div>
    <div class="bss-product-info-price">
        <div class="price-box" data-role-fastorder="priceBox">
            <span class="price-container">
                <span id="bss-product-price-<?php echo $_product->getId(); ?>"
                      data-price-amount="<?php echo $_product->getFinalPrice(); ?>" data-price-type="finalPrice"
                      class="price-wrapper final-price"></span>
                <?php if($this->helper('Magento\Tax\Helper\Data')->displayBothPrices()) : ?>
                    <p><?php echo __('Excl. Tax: ') ?>
                        <span id="bss-product-price-excl-tax-<?php echo $_product->getId(); ?>"
                            data-price-amount="<?php echo $_product->getFinalPrice(); ?>" data-price-type="basePrice"
                            class="price-wrapper base-price"></span>
                    </p>
                <?php endif; ?>
            </span>
        </div>
    </div>
</div>

<form id="bss-fastorder-form-option" method="post"
      data-hasrequired="<?php /* @escapeNotVerified */
      echo __('* Required Fields') ?>"
>
    <div class="bss-product-option">
        <input type="hidden" class="bss-product-child-id" value="<?php echo $_product->getId(); ?>">
        <?php
        $productType = $_product->getTypeId();
        switch ($productType) {
            case 'configurable':
                echo $this->getLayout()->createBlock('Bss\FastOrder\Block\Product\Renderer\Configurable')
                    ->setTemplate('Bss_FastOrder::configurable.phtml')->setProduct($_product)->toHtml();
                break;
            case 'downloadable':
                echo $this->getLayout()->createBlock('\Magento\Downloadable\Block\Catalog\Product\Links', '',
                    [
                        'data' => [
                            'sort_order' => $sortOrder
                        ]
                    ])
                    ->setTemplate('Bss_FastOrder::downloadable.phtml')->setProduct($_product)->toHtml();
                break;
            case 'grouped':
                echo $this->getLayout()->createBlock('\Magento\GroupedProduct\Block\Product\View\Type\Grouped', '',
                    [
                        'data' => [
                            'sort_order' => $sortOrder
                        ]
                    ])
                    ->setTemplate('Bss_FastOrder::grouped.phtml')
                    ->setProduct($_product)->toHtml();
                break;
            // case 'bundle':
            //   echo $this->getLayout()->getBlock('product.info.bundle.options')
            //     // ->setTemplate('Bss_FastOrder::bundle.phtml')
            //     ->setProduct($_product)
            //     ->toHtml();
            //   break;
        }
        echo $this->getLayout()->getBlock('product.info.options')
            ->setProduct($_product)
            ->toHtml();
        ?>
        <div class="bss-box-button">
            <div class="fieldset"></div>
            <div class="actions">
                <button type="button" title="Cancel" class="action" id="bss-cancel-option">
                    <span><?php /* @escapeNotVerified */
                        echo __('Cancel') ?></span>
                </button>
                <button type="submit" title="Select" class="action primary" id="bss-select-option">
                    <span><?php /* @escapeNotVerified */
                        echo __('Select') ?></span>
                </button>
            </div>
        </div>
    </div>
</form>
<script>
    require(["jquery", "jquery/ui", 'Magento_Catalog/js/price-box', 'Magento_Catalog/product/view/validation'], function ($) {
        var priceBoxesFastOrder = $('[data-role-fastorder=priceBox]');
        priceBoxesFastOrder.priceBox({
            'priceConfig': <?php /* @escapeNotVerified */ echo $_helper->getJsonConfigPrice($_product);?>,
        });
        priceBoxesFastOrder.trigger('reloadPrice');
        $('.loading-mask').show();
        $('#bss-fastorder-form-option').validation({});

    });
</script>