<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php
// @codingStandardsIgnoreFile

/** @var \Amasty\Promo\Block\Items $block */
use Magento\Framework\App\Action\Action;

$products = $block->getItems();
$imageHelper = $block->getImageHelper();
$popupMode = $block->getPopupMode();
$isShowPrice = $block->getShowPriceInPopup();
?>

<?php if ($products) : ?>
<div class="ampromo-carousel-product" data-role="ampromo-carousel-product">
    <div class="ampromo-gallery" data-count="<?= $products ? count($products) : 0 ?>" data-role="ampromo-gallery">
        <?php foreach ($products as $product) : ?>
            <?php
            $product = $block->getProductById($product->getId());
            $isVisible = $product->getVisibility() != Magento\Catalog\Model\Product\Visibility::VISIBILITY_NOT_VISIBLE;
            $optionsBlock = $block->getChildBlock($product->getTypeId() . '_prototype');
            ?>
                <div class="ampromo-item"
                     data-product-id="<?= $product->getId()?>"
                     data-product-sku="<?= $product->getSku()?>"
                     data-role="ampromo-item">
                    <form method="POST"
                          action="<?= $block->getFormActionUrl()?>"
                          data-role="ampromo-items-form"
                          class="ampromo_items_form"
                          id="ampromo_items_form-<?= $product->getId()?>">
                        <input type="hidden"
                               name="<?= Action::PARAM_NAME_URL_ENCODED; ?>"
                               value="<?= $block->getCurrentBase64Url() ?>">
                        <?php if ($popupMode) : ?>
                        <div class="ampromo-product-select" data-role="ampromo-product-select">
                            <input type="checkbox"/>
                        </div>
                        <?php endif; ?>
                        <div class="ampromo-item-title">
                            <?php if ($isVisible) : ?>
                                <h4><a href="<?= $product->getProductUrl()?>"><?= $product->getName()?></a></h4>
                            <?php else : ?>
                                <h4><?= $product->getName()?></h4>
                            <?php endif?>
                        </div>
                        <?php $imageHelper->init($product, 'cart_page_product_thumbnail')
                            ->keepFrame(false)
                            ->constrainOnly(true)
                            ->resize(160, 160)
                        ;
                        ?>
                        <img src="<?= $imageHelper->getUrl() ?>"
                             class="ampromo-item-image"
                             alt="<?= $block->stripTags($product->getName(), null, true) ?>"/>

                        <input type="hidden" value="<?= $product->getId() ?>" name="product_id" />

                        <div class="product-options-wrapper" id="product-options-wrapper">
                            <fieldset class="fieldset" tabindex="0">
                                <?php if ($optionsBlock) : ?>
                                    <?= $optionsBlock->setProduct($product)->toHtml(); ?>
                                <?php endif ?>
                                <?= $block->getOptionsHtml($product); ?>
                            </fieldset>
                        </div>
                        <?php if ($isShowPrice) : ?>
                            <div class="product-info-price">
                                <div class="price-base_price price-box-<?=$product->getId()?>"
                                     data-product-id="<?=$product->getId() ?>"
                                     data-role="priceBox">
                                    <span class="price-container price-base_price tax weee">
                                        <span id="product-price-<?=$product->getId() ?>"
                                              data-price-amount="<?=$block->getProductPrice($product)?>"
                                              data-price-type="basePrice"
                                              class="price-wrapper ">
                                            <span class="price"></span>
                                        </span>
                                    </span>
                                </div>
                                <div class="price-new_price price-box-<?=$product->getId()?>"
                                     data-product-id="<?=$product->getId() ?>"
                                     data-role="priceBox">
                                    <span class="price-new_price tax weee">
                                        <span id="product-price-<?=$product->getId() ?>"
                                              data-price-amount="<?=$block->getProductPrice($product)?>"
                                              data-price-type="newPrice"
                                              class="price-wrapper ">
                                            <span class="price"></span>
                                        </span>
                                    </span>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?php if ($popupMode) : ?>
                            <div class="ampromo-item-qty-input" data-role="ampromo-item-qty-input">
                                <input class="ampromo-item-qty-select-input"
                                       type="number"
                                       name="ampromo_qty_select_<?=$product->getId()?>"
                                       id="ampromo_qty_select_<?=$product->getId()?>"
                                       min="0"
                                       value="0"
                                       disabled="disabled"
                                       data-validate="{
                                           required:true,
                                           'validate-digits':true,
                                           'validate-zero-or-greater':true}"
                                         title="QTY Select"/>
                                <span class="ampromo-item-qty-left">
                                    <span>1</span><?= __(' left') ?>
                                </span>
                            </div>
                        <?php else : ?>
                        <div class="ampromo-item-buttons" data-role="ampromo-item-buttons">
                            <button class="action tocart primary"
                                    type="submit"
                                    title="<?= __('Add to cart')?>"><span><?= __('Add to cart')?></span>
                            </button>
                        </div>
                        <?php endif; ?>
                    </form>
                    <?php if ($product->getTypeId() !== \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) : ?>
                    <script>
                        require([
                            'jquery',
                            'Amasty_Promo/js/price-updater'
                        ], function($) {
                            $(window).on('load', function () {
                                $('div.ampromo-items').ampromoPriceUpdater({
                                    productId: <?= $block->escapeHtml($product->getId()) ?>,
                                    priceConfig: <?= /* @escapeNotVerified */ $block->getJsonConfig($product) ?>
                                });
                            });

                            $('a[data-role="ampromo-popup-show"]').on('click', function () {
                                $('div.ampromo-items').ampromoPriceUpdater({
                                    productId: <?= $block->escapeHtml($product->getId()) ?>,
                                    priceConfig: <?= /* @escapeNotVerified */ $block->getJsonConfig($product) ?>
                                });
                            })
                        });
                    </script>
                    <?php endif; ?>
                </div>
            <?php endforeach ?>
    </div>
    <?php if ($popupMode) : ?>
    <div class="ampromo-item-buttons" data-role="ampromo-item-buttons">
        <button class="action tocart primary"
                type="button"
                title="<?= __('Add to cart')?>"><span><?= __('Add to cart')?></span>
        </button>
    </div>
    <?php endif; ?>
</div>
<?php endif; ?>
