<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<div class="block block-reward-info">
    <div class="block-title">
        <strong>Redeem points balance Information</strong>
    </div>
    <div class="block-content">
        <?php $balancePoints = $block->getBalanceRewardPoints();?>
        <p class="reward-balance">Your balance points : <b><?php echo $balancePoints;?></b></p>
    </div>
    <div class="block block-reward-history">
    </div>
    <?php if($balancePoints):?>
    <form class="form reward-settings" action="<?php echo $block->getUrl('amasty_promo/customer/send');?>" method="post" id="form-validate">
         <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="Submit"><span>Redeem Points</span></button>
            </div>
        </div>
    </form>
    <?php endif;?>
</div>
