<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
        <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>
    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
<?php
$incrementId = $this->getOrderId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore()->getBaseUrl();
$order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($incrementId);
$email = $order->getCustomerEmail();
$transId =  $order->getPayment()->getLastTransId();
$itemsList = '';
    $i = 1;
    $items = $order->getAllItems();
    $orderCount = count($items);
    foreach($items as $item) {
    if($item->getPrice() != 0) {
        if($i != 1)
            $itemsList .= ', ';
        $itemsList .= '{ id: "'.$item->getSku().'", price: '.$item->getPrice().' , quantity: '.$item->getQtyOrdered().' }';
        //if($i < $orderCount)
          //  $itemsList .= ', ';

        $i++;
    }
    }
//echo $itemsList;
?>
<?php
$incrementIdSidecar = $this->getOrderId();
$objectManagerSidecar = \Magento\Framework\App\ObjectManager::getInstance();

$orderSidecar = $objectManagerSidecar->create('Magento\Sales\Model\Order')->loadByIncrementId($incrementIdSidecar);
$shippingAddress = $orderSidecar->getShippingAddress();
$itemsListSidecar = '';
$iSidecar = 1;
$itemsSidecar = $orderSidecar->getAllItems();
foreach($itemsSidecar as $itemSidecar) {
    if($itemSidecar->getPrice() != 0) {
        if($iSidecar != 1)
            $itemsListSidecar .= ', ';
        $itemsListSidecar .= '{ product_id: "'.$itemSidecar->getSku().'", unit_price: '.$itemSidecar->getPrice().' , quantity: '.$itemSidecar->getQtyOrdered().' }';
        $iSidecar++;
    }
}
$discountListSidecar = '';
if($orderSidecar->getDiscountDescription() != "" && $orderSidecar->getDiscountDescription() != NULL) {
    $orderDiscountCode = $orderSidecar->getDiscountDescription();
    $orderDiscountAmount = number_format(abs($orderSidecar->getDiscountAmount()), 2, '.', '');
    $discountListSidecar .= '{ name: "'.$orderDiscountCode.'", amount: "'.$orderDiscountAmount.'" }';
}
?>
<script type="text/javascript">
	var sidecar = sidecar || {};
	sidecar.transactions = {
	add: true,
	data: {
		order_id: '<?php echo $incrementIdSidecar;?>',
		subtotal: '<?php echo number_format((float)$orderSidecar->getSubtotal(), 2, '.', '');?>',
		tax: '<?php echo number_format((float)$orderSidecar->getTaxAmount(), 2, '.', '');?>',
		shipping: '<?php echo number_format((float)$orderSidecar->getShippingAmount(), 2, '.', '');?>',
		discounts: '<?php echo number_format(abs($orderSidecar->getDiscountAmount()), 2, '.', '');?>',
		total: '<?php echo number_format((float)$orderSidecar->getGrandTotal(), 2, '.', '');?>',
		zipcode: '<?php echo $shippingAddress->getPostcode();?>'
	},
	items: [
		<?php echo $itemsListSidecar;?>
	],
	discounts: [
		<?php echo $discountListSidecar;?>
	]
	};
</script>

<?php
/**
 * ICUBE
 * Description: Disabling hardcoded script, temporary fixed until further notice (the script below is calling Amasty_Promo Ajax with specific customer data)
 */?>
<!-- <div class='SuccessView'></div>

<script type="text/javascript">
    function ajaxSuccess() {
        var myVariable;
        var email = '<?php //echo $email;?>';
        var lastTransId = '<?php //echo $transId;?>';
        var orderItems = '<?php //echo $itemsList;?>';
        var url = '<?php //echo $url;?>';
        jQuery.ajax({
            'async': false,
            'type': "POST",
            'global': false,
            'dataType': 'html',
            'url': url+"amasty_promo/customer/info?ajax=SuccessView&account=32513"+'&email='+email+'&lastTransId='+lastTransId+'&orderItems='+orderItems,
            'success': function (data) {
                myVariable = data;
            }
        });
        return myVariable;
    }
    var success = ajaxSuccess();
    jQuery('.SuccessView').html(success);
</script> -->

<?php 
	$shippingAddress = $order->getShippingAddress();
	$estimatedDate = date('Y-m-d', strtotime("+7 days"));
?>
<script src="https://apis.google.com/js/platform.js?onload=renderOptIn" async defer></script>  
<script>   
window.renderOptIn = function() {     
	window.gapi.load('surveyoptin', function() {
	window.gapi.surveyoptin.render({
		"merchant_id": 113828842,
		"order_id": <?php echo $order->getId(); ?>,
		"email": '<?php echo $order->getCustomerEmail(); ?>',
		"delivery_country": '<?php echo $shippingAddress->getCountryId();?>',
		"estimated_delivery_date": '<?php echo $estimatedDate; ?>'
		});     
	});
} 
</script>
 
<script src="https://apis.google.com/js/platform.js?onload=renderBadge" async defer></script>  
<script>
	window.renderBadge = function() {
		var ratingBadgeContainer = document.createElement("div");
		document.body.appendChild(ratingBadgeContainer);
		window.gapi.load('ratingbadge', function() {
			window.gapi.ratingbadge.render(ratingBadgeContainer, {"merchant_id": 113828842});     
		});
	}
</script>
