<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<?php $logDet = $block->getLogDetails();?>

<?php $dateObject = $block->getDateObject(); ?>
<?php
$scheduleAt = new \DateTime($logDet['scheduled_at']);
$scheduleAtTimeStamp  = $scheduleAt->getTimestamp();
?>
<?php
$finishedAt = new \DateTime($logDet['finished_at']);
$finishedAtTimeStamp  = $finishedAt->getTimestamp();
?>
<?php
$diff = ($finishedAtTimeStamp - $scheduleAtTimeStamp);
$second = 1;
$minute = 60 * $second;
$hour = 60 * $minute;
$day = 24 * $hour;
$getResult["day"] = floor($diff / $day);
$getResult["hour"] = floor(($diff % $day) / $hour);
$getResult["minute"] = floor((($diff % $day) % $hour) / $minute);
$getResult["second"] = floor(((($diff % $day) % $hour) % $minute) / $second);
?>
<?php $syncDuration = $getResult["day"] . ' days , ' . $getResult["hour"] . " : " . $getResult["minute"] . " : " . $getResult["second"]; ?>
<?php if(isset($_SERVER["HTTP_REFERER"])) { ?>
    <input type="button" class="action-default scalable action-secondary" value="Back" onclick="window.location.href='<?php echo $block->getBackUrl(); ?>'" /> <br>
<?php }?><br>
<?php $style = 'style="float:left;padding:5px;width:25%;text-align:left;padding-left:15px"';?>
<div class="entry-edit">
    <div class="entry-edit">
        <div class="example-responsive-block">
            <h4 class="" style="background-color: #41362f;color:#fff;line-height: 20px;padding:10px"><?php echo'Log Data'; ?></h4>
        </div>
        <div id="log_details_fieldset" class="log-details">
            <table style="border: 1px solid #d6d6d6;" cellspacing="2" class="log-info table">
                <col width="100%" />
                <col />
                <tbody>
            <tr>
                <td width='25%' <?php echo $style; ?>><b>Sync Entity:</b></td>
                <td width='25%' <?php echo $style; ?>><?php echo $logDet['job_code']; ?></td>
                <td width='25%' <?php echo $style; ?>><b>Scheduled At :</b></td>
                <td width='25%' <?php echo $style; ?>><?php echo $dateObject->date($logDet['scheduled_at'],null,true)->format('M d, Y h:i:s A');?></td>
            </tr>

            <tr>
                <td width='25%' <?php echo $style; ?>><b>Sync Status:</b></td>
                <td width='25%' <?php echo $style; ?>><?php echo $logDet['status']; ?></td>
                <td width='25%' <?php echo $style; ?>><b>Executed At :</b></td>
                <td width='25%' <?php echo $style; ?>><?php echo $dateObject->date($logDet['executed_at'],null,true)->format('M d, Y h:i:s A');?></td>
            </tr>

            <tr>
                <td width='25%' <?php echo $style; ?>><b>Created At:</b></td>
                <td width='25%' <?php echo $style; ?>><?php echo $dateObject->date($logDet['created_at'],null,true)->format('M d, Y h:i:s A');?></td>
                <td width='25%' <?php echo $style; ?>><b>Finished At :</b></td>
                <td width='25%'
                    <?php echo $style; ?>><?php  echo $dateObject->date($logDet['finished_at'],null,true)->format('M d, Y h:i:s A');?></td>
            </tr>

            <tr>
                <td width='25%' <?php echo $style; ?>><b>Sync Duration:</b></td>
                <td <?php echo $style; ?>><?php echo $syncDuration; ?></td>
                <td></td>
                <td></td>
            </tr>
                </tbody>
        </table>
        </div>
    </div>
</div>


<?php
echo $block->getGridHtml();
?>
