<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<?php
$logData = $block->getLog();
$prodName = $block->getProductName($logData[0]['product_id']);
?>
<?php $style = 'style="float:left;padding:5px;width:25%;text-align:left;padding-left:15px;word-wrap: break-word;"';?>
<?php if(isset($_SERVER["HTTP_REFERER"])) { ?>
    <input type="button" class="action-default scalable action-secondary" value="Back" onclick="window.location.href='<?php echo $_SERVER["HTTP_REFERER"]; ?>'" /> <br>
<?php }?><br>
<div class="example-responsive-block">
    <h4 class="" style="background-image: linear-gradient(hsla(207, 10%, 35%, 0.97), hsla(207, 5%, 25%, 0.92));color:#fff;line-height: 20px;padding:10px"><?php echo'Log Data'; ?></h4>
</div>
<table style="border: 1px solid #d6d6d6;width:100%" cellspacing="2" class="log-info table">
    <col width="100%" />
    <col />
    <tbody>
    <tr>
        <td width='25%' <?php echo $style; ?>><h3><b>Aggregated Information</b></h3></td>
        <td width='75%' <?php echo $style; ?>></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Action:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['sync_action']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Sync Date:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['created_at']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Sync Status : </b></td>
        <td width='75%' <?php echo $style; ?>><?php if ($logData[0]['message_type'] == 0 ) { echo "Success"; } else { echo "Failure"; }  ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Magento Product Id:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['product_id']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Magento Product Name:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $prodName; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Acumatica Stock Item:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['acumatica_stock_item']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Sync Action:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['sync_action']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Before Change:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo wordwrap($logData[0]['before_change'], 150, "<br>\n"); ?></td>
    </tr>
    </tbody>
</table>


<?php
$logDetail = $block->getLogDetails();
?>


<?php if ( isset($logDetail[0]['long_message']) &&  $logDetail[0]['long_message'] != '') { ?>
    <div class="example-responsive-block">
        <h4 class="" style="background-image: linear-gradient(hsla(207, 10%, 35%, 0.97), hsla(207, 5%, 25%, 0.92));color:#fff;line-height: 20px;padding:10px"><?php echo'Error trace'; ?></h4>
    </div>
    <table style="background-color:lightgrey;width:100%;">
        <tr>
            <td width='75%' <?php echo $style; ?>> <?php echo $logDetail[0]['long_message']; ?> </td>
        </tr>
    </table>

<?php } ?>
