<table class="form-list" cellspacing="0" cellpadding="0">

    <tr>
        <td class="label">
            <label><?php echo 'Type'; ?>: </label>
        </td>
        <td class="value">
            <?php echo "Magento"; ?>
        </td>
    </tr>



    <tr>
        <td class="label">
            <label><?php echo 'Last Run'; ?>: </label>
        </td>

        <td class="value">
            <span><?php echo "N/A"; ?></span>

        </td>
    </tr>


        <tr>
            <td class="label" colspan="2" style="width: 600px">
                <strong><?php echo 'We recommend to set up your cron job to be run every 1 minute (e.g. * * * * *).'; ?></strong>
            </td>
        </tr>

        <tr>
            <td class="label">
                <label><?php echo 'PHP command'; ?>: </label>
            </td>
            <td class="value">
                <?php echo $block->cronPhp;  ?>
            </td>
        </tr>

        <tr>
            <td class="label">
                <label><?php echo 'GET command'; ?>: </label>
            </td>
            <td class="value">
                <?php echo $block->cronGet;?>
            </td>
        </tr>





</table>
