<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<div style="height: 500px;" id="support_system_requirements_container">
    <div class="entry-edit-head">
        <h4 class="" style="background-image: linear-gradient(hsla(207, 10%, 35%, 0.97), hsla(207, 5%, 25%, 0.92));color:#fff;line-height: 20px;padding:10px"><?php echo'Documentations'; ?></h4>
    </div>
    <div class="fieldset">
        <div class="fieldset">
            <div style="margin: 10px 10px 10px 10px">
                <span class="doc-title"><b style="color: #EE6400">Sync Documentation </b></span><span class="up-arrow help" id="hide">[Help] ↑</span><span class="down-arrow help" id="show" style="display: none;">[Help] ↓ </b></span>
            </div>
            <div style="margin: 10px 10px 10px 10px">
                <p>Acumatica-Magento Connector 2.1 Feature list, Limitations, Assumptions, User Guide documents are available on the <a href="#" style="color: #EE6400;  text-decoration: underline;">Acumatica-Magento Connector Documents</a> link.</p>
            </div>
        </div>
    </div>
</div>
<style>
    .fieldset {
        background: #fafafa none repeat scroll 0 0;
        border: 1px solid #d6d6d6;
    }
</style>
