<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
/**
 * acumaticaBaseData.phtml
 */
?>
<?php
$ajaxUrl = explode('||',$block->getAjaxUrl());
$acumaticaBaseUrl = $ajaxUrl[0];
$logviewurl         = $ajaxUrl[1];
$baseurl            = $ajaxUrl[2];
?>
<script>
    /* Acumatica Base Data */
    function acumaticaBaseData() {
        require([
            "jquery",
            "Kensium_Amconnector/js/jquery.colorbox-min"
        ], function (jQuery) {
            var logviewurl = '<?php echo $logviewurl; ?>';
            var baseurl = '<?php echo $baseurl; ?>';
            var acumaticabaseurl = '<?php echo $acumaticaBaseUrl; ?>';
            var synctitle = 'Base data';
            jQuery.colorbox({html:"",rel:'group3',href: logviewurl,iframe:true, innerWidth:"50%", innerHeight:"50%",title:"<div style  = 'float:left;width:100%;background-size:100% 100%;height:50px;background-image:url("+baseurl+"adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/header_bg.gif);' > <span style='height: 36px; width: 35px; padding: 2px; text-align: center; margin: 6px -5px 0px 10px; float: left; background:#fff url("+baseurl+"adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/amconnector/amconnector_medium.png) no-repeat 2px 2px; border-radius: 20px;' ></span>  <span style = 'float:left;font-size:20px;font-weight:bold;color:white;padding: 14px; ' >Acumatica - " + synctitle + "</span> </div>",onClosed:function() { location.reload(true); }});
            jQuery.ajax({
                url:acumaticabaseurl,
                method:"GET",
                data: {
                    store:'<?php echo $this->getRequest()->getParam('store', NULL) ?>'
                }
            });
        });
    }
</script>
<div class="pp-buttons-container">
    <div id="connection_status" class="message-validation hidden"></div>
    <button id="<?php echo $block->getHtmlId(); ?>" onclick="javascript:acumaticaBaseData(); return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
    </button>
</div>