<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
/**
 * getCustomerTerms.phtml
 */
?>
<script>
    require(['prototype'], function () {
        function getCustomerTermsData() {
            var websiteCode = '<?php echo $this->getRequest()->getParam("website"); ?>';
            var store = '<?php echo $this->getRequest()->getParam("store"); ?>';
            if(websiteCode != ''){
                var website = websiteCode;
                var storeCode = "";
            }else{
                var website = 'default';
                var storeCode = "";
            }
            if(store != ''){
                var website = "stores";
                var storeCode = store;
            }
            params = {
                scope : website,
                store : storeCode
            };
            new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
                parameters: params,
                onSuccess: function (response) {
                    location.reload();
                }
            });
        }
        window.getCustomerTermsData = getCustomerTermsData;
    });
</script>
<div class="pp-buttons-container">
    <div id="connection_status" class="message-validation hidden"></div>
    <button id="<?php echo $block->getHtmlId(); ?>" onclick="javascript:getCustomerTermsData(); return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
    </button>
</div>