<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>

<script type="text/javascript">
    //<![CDATA[
    //get multiple selected options like domains,macids
    function getSelectedOptions(element) {
        // validate element
        if (!element || !element.options)
            return []; //or null?

        // return HTML5 implementation of selectedOptions instead.
        if (element.selectedOptions)
            return element.selectedOptions;

        // you are here because your browser doesn't have the HTML5 selectedOptions
        var opts = element.options;
        var selectedOptions = [];
        for (var i = 0; i < opts.length; i++) {
            if (opts[i].selected) {
                selectedOptions.push(opts[i]);
            }
        }
        return selectedOptions;
    }
    //License request sent
    function check() {
        var domain = getSelectedOptions(document.getElementById("license_add_domain_request_add_domainnames"));
        var domains = "";
        for (var i = 0; i < domain.length; i++) {
            domains += domain[i].value + ",";
        }

        var macid = getSelectedOptions(document.getElementById("license_add_domain_request_add_macids"));
        var macids = "";
        for (var i = 0; i < macid.length; i++) {
            macids += macid[i].value + ",";
        }

        var ipaddress = document.getElementById('license_add_domain_request_add_ipaddress').value;
        var email = document.getElementById('license_add_domain_request_add_email_recipient').value;
        var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
        if (!re.test(email)) {
            alert("Please provide a valid email address.");
            return false;
        }
        var license_type = document.getElementById('license_add_domain_request_add_license_type').value;
        var comments = document.getElementById('license_add_domain_request_addcomments').value;
        var terms = document.getElementById('terms').checked;
        if (terms) {
            terms = 1;
        } else {
            alert("Please Accept Terms & Conditions to proceed further.");
            return false;
        }
        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            method: 'get',
            parameters: {
                "domain": domains,
                "macid": macids,
                "ipaddress": ipaddress,
                "email": email,
                "license_type": license_type,
                "terms": terms,
                "comment": comments
            },

            onSuccess: function (transport) {
                //return true;
                if (transport.responseText) {
                    location.reload();
                }
            }
        });

    }
    //Export license request
    function exportcheck(url) {
        var domain = getSelectedOptions(document.getElementById("license_domain_change_domain_urls"));
        var domains = "";
        for (var i = 0; i < domain.length; i++) {
            domains += domain[i].value + ",";
        }
        var macid = getSelectedOptions(document.getElementById("license_license_request_mac_id"));
        var macids = "";
        for (var i = 0; i < macid.length; i++) {
            macids += macid[i].value + ",";
        }
        console.log(macids);
        var ipaddress = document.getElementById('license_domain_change_ip_address').value;
        var email = document.getElementById('emailrecipient').value;
        var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
        if (!re.test(email)) {
            alert("Please provide a valid email address.");
            return false;
        }
        var license_type = document.getElementById('license_domain_change_license_type').value;
        var terms = document.getElementById('terms').checked;
        if (terms) {
            terms = 1;
        } else {
            alert("Please Accept Terms & Conditions to proceed further.");
            return false;
        }
        new Ajax.Request('<?php echo $this->getAjaxExportCheckUrl() ?>', {
            method: 'get',
            parameters: {
                "domain": domains,
                "macid": macids,
                "ipaddress": ipaddress,
                "email": email,
                "license_type": license_type,
                "terms": terms
            },

            onSuccess: function (transport) {
                setLocation(url);
            }
        });

    }
    //]]>
</script>
<div class="pp-buttons-container">
    <div id="add_license_request" class="message-validation hidden"></div>
    <button id="<?php echo $block->getHtmlId(); ?>" onclick= "javascript:check(); return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
    </button>
</div>
