<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
/**
 * sendlicenserequest.phtml
 */

?>
<script>
    //<![CDATA[
  //  require(['prototype'], function () {
        //get multiple selected options like domains,macids
        function getSelectedOptions(element) {
            // validate element
            if (!element || !element.options)
                return []; //or null?

            // return HTML5 implementation of selectedOptions instead.
            if (element.selectedOptions)
                return element.selectedOptions;

            // you are here because your browser doesn't have the HTML5 selectedOptions
            var opts = element.options;
            var selectedOptions = [];
            for (var i = 0; i < opts.length; i++) {
                if (opts[i].selected) {
                    selectedOptions.push(opts[i]);
                }
            }
            return selectedOptions;
        }
        //License request sent
        function checkLicense() {
            var domain = getSelectedOptions(document.getElementById("license_license_request_domainnames"));
            var domains = "";
            for (var i = 0; i < domain.length; i++) {
                domains += domain[i].value + ",";
            }

            var macid = getSelectedOptions(document.getElementById("license_license_request_macids"));
            var macids = "";
            for (var i = 0; i < macid.length; i++) {
                macids += macid[i].value + ",";
            }

            var ipaddress = document.getElementById('license_license_request_ipaddress').value;
            var email = document.getElementById('license_license_request_emailrecipient').value;
            var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
            if (!re.test(email)) {
                alert("Please provide a valid email address.");
                return false;
            }
            var license_type = document.getElementById('license_license_request_licensetype').value;
            var terms = document.getElementById('terms').checked;

            if (terms) {
                terms = 1;
            } else {
                alert("Please Accept Terms & Conditions to proceed further.");
                return false;
            }
            var comments = document.getElementById('license_license_request_comments').value;
            /*console.log("domains =="+domains);
            console.log("macids =="+macids);
            console.log("ipaddress =="+ipaddress);
            console.log("email =="+email);
            console.log("license_type =="+license_type);
            console.log("terms =="+terms); */
            //return false;
            new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
                method: 'post',
                parameters: {
                    domain: domains,
                    macid: macids,
                    ipaddress: ipaddress,
                    email: email,
                    license_type: license_type,
                    terms: terms,
                    comment: comments
                },

                onSuccess: function (transport) {
                    //return true;
                    if (transport.responseText) {
                        location.reload();
                    }
                }
            });

        }

  //  });
    //]]>

</script>
<div class="pp-buttons-container">
    <div id="send_license_request" class="message-validation hidden"></div>
    <button id="<?php echo $block->getHtmlId(); ?>" onclick= "javascript:checkLicense(); return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
    </button>
</div>