<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
/**
 * verifyTimeSetting.phtml
 */
?>
<script>
    require(['prototype'], function () {
        function verifyTimeSetting() {
            var websiteCode = '<?php echo $this->getRequest()->getParam("website"); ?>';
            var store = '<?php echo $this->getRequest()->getParam("store"); ?>';
            if(websiteCode != ''){
                var website = websiteCode;
                var storeCode = "";
            }else{
                var website = 'default';
                var storeCode = "";
            }
            if(store != ''){
                var website = "stores";
                var storeCode = store;
            }
            var validationMessage = $('time_setting_status');
            var autoTimeSync = document.getElementById('amconnector_time_configuration_amconnectortimeset_automatictimesync').value;
            params = {
                scope : website,
                storeId : storeCode,
                autoTimeSync: autoTimeSync
            };
            new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
                parameters: params,
                onSuccess: function (response) {
                    location.reload();
                }
            });
        }
        window.verifyTimeSetting = verifyTimeSetting;
    });
    //onLoad Time-Sync status
    window.onload = function(){
        var button = document.getElementById('amconnector_time_configuration_amconnectortimeset_verify_time_setting');
        var buttonLabel = 'Verify';
        var validationMessage = document.getElementById('time_setting_status');
        var validationUrl = '<?php /* @escapeNotVerified */ echo $block->getValidationUrl() ?>';
        new Ajax.Request(validationUrl, {
            onSuccess: function (response) {
                var result = '<?php /* @escapeNotVerified */ echo __('Verify Acumatica Test Connection.') ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        var timeSyncStatus = response.timeSyncStatus;
                        if (timeSyncStatus == 1) {
                            result = '<h3 style="color: #008000;">Magento server time is in sync.</h3>';
                            validationMessage.removeClassName('hidden').addClassName('success');
                        }else if (timeSyncStatus == 2) {
                            buttonLabel = 'Sync Now';
                            result = '<h3 style="color: #FF0000;">Magento server time does not match with Acumatica server timezone.</h3>';
                            validationMessage.removeClassName('hidden').addClassName('error');
                        } else {
                            result = '';
                            validationMessage.removeClassName('hidden').addClassName('error');
                        }
                    }
                } catch (e) {
                    validationMessage.removeClassName('hidden').addClassName('error');
                }
                validationMessage.update(result);
                document.getElementById('verify-button-label').textContent = buttonLabel;
            }
        });
    }
</script>
<div class="pp-buttons-container">
    <div id="time_setting_status" class="message-validation hidden"></div>
    <button id="<?php echo $block->getHtmlId(); ?>" style="margin-top: 10px;" onclick="javascript:verifyTimeSetting(); return false;">
        <span id="verify-button-label"><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
