<?php
    $footer = $this->getConfig('porto_settings/footer');
?>
<div class="footer">
<?php
    if( $footer['footer_top'] ){
?>
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                <?php
                    $area = 'footer_top_block';
                    $type = $footer[$area];
                    if( $type == 'custom' && $footer['footer_top_custom'] ){
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if($block) {
                            $block->setBlockId($footer['footer_top_custom']);
                        }
                        if($block){
                            echo '<div class="custom-block">'.$block->toHtml().'</div>';
                        }
                    }

                ?>
                </div>
            </div>
        </div>
    </div>
<?php
    }
    if( $footer['footer_middle'] ){
?>
    <div class="footer-middle">
        <div class="container">
        <?php
            if( $footer['footer_ribbon'] ){
        ?>
            <div class="footer-ribbon">
                <span><?php echo $footer['footer_ribbon_text'] ?></span>
            </div>
        <?php
            }
        ?>
            <div class="row">
            <?php
                for( $i = 1; $i <= 4; $i++ ){
                    $area = 'footer_middle_column_'.$i;
                    $type = $footer[$area];
                    if( $type ){
                        echo '<div class="col-sm-'.$footer[$area.'_size'].'">';
                    }
                    if( $type == 'custom' && $footer[$area.'_custom'] ){
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if($block) {
                            $block->setBlockId($footer[$area.'_custom']);
                        }
                        if($block){
                            echo $block->toHtml();
                        }
                    }
                    if( $type == 'newsletter' ){
                        echo $this->getChildHtml('footer.newsletter');
                    }
                    if( $type ){
                        echo '</div>';
                    }
                }
            ?>
            </div>
        </div>
    </div>
<?php
    }
    if( $footer['footer_middle_2'] ){
?>
    <div class="footer-middle footer-middle-2">
        <div class="container">
            <div class="row">
            <?php
                for( $i = 1; $i <= 4; $i++ ){
                    $area = 'footer_middle_2_column_'.$i;
                    $type = $footer[$area];
                    if( $type ){
                        echo '<div class="col-sm-'.$footer[$area.'_size'].'">';
                    }
                    if( $type == 'custom' && $footer[$area.'_custom'] ){
                        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                        if($block) {
                            $block->setBlockId($footer[$area.'_custom']);
                        }
                        if($block){
                            echo $block->toHtml();
                        }
                    }
                    if( $type == 'newsletter' ){
                        echo $this->getChildHtml('footer.newsletter');
                    }
                    if( $type ){
                        echo '</div>';
                    }
                }
            ?>
            </div>
        </div>
    </div>
<?php
    }
    if( $footer['footer_bottom'] ){
?>
    <div class="footer-bottom">
        <div class="container">
         <address><?php echo $footer['footer_bottom_copyrights'] ?></address>
            <?php
            if($footer['footer_logo_src']){
                
                $url = $this->getFooterLogoSrc();
            ?>
            <?php if ($this->isHomePage()):?>
                <strong class="logo">
            <?php else: ?>
                <a class="logo" href="<?php echo $this->getUrl(''); ?>" title="">
            <?php endif; ?>
                <img src="<?php echo $url ?>" alt=""/>
            <?php if ($this->isHomePage()):?>
                </strong>
            <?php else:?>
                </a>
            <?php endif?>
            <?php
            }
            if($footer['footer_bottom_custom_1']){
                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                if($block) {
                    $block->setBlockId($footer['footer_bottom_custom_1']);
                }
                if($block){
                    echo '<div class="custom-block">'.$block->toHtml().'</div>';
                }
            }
            ?>
            <?php
            if($footer['footer_bottom_custom_2']){
                $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                if($block) {
                    $block->setBlockId($footer['footer_bottom_custom_2']);
                }
                if($block){
                    echo '<div class="custom-block f-right">'.$block->toHtml().'</div>';
                }
            }
            ?>
           
            <?php if($footer['footer_store_switcher']) echo $this->getChildHtml("footer.store_switcher"); ?>
        </div>
    </div>
<?php
    }
?>
</div>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
    ->getStore()->getBaseUrl();
if( $this->getRequest()->getFullActionName() == 'cms_index_index') {
?>

    <div class='viewHome'></div>

    <script type="text/javascript">
        function ajaxEmail() {
            var myVariable;
            var url = '<?php echo $url;?>';
            jQuery.ajax({
                'async': false,
                'type': "POST",
                'global': false,
                'dataType': 'html',
                'url': url+"amasty_promo/customer/info?ajax=viewHome&account=32509",
                'success': function (data) {
                    myVariable = data;
                }
            });
            return myVariable;
        }
        var email = ajaxEmail();
        jQuery('.viewHome').html(email);

    </script>

<?php } else if($this->getRequest()->getFullActionName() == 'catalog_product_view') { 

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
    $sku = $product->getSku();
?>
    <div class='productView'></div>

    <script type="text/javascript">
        function ajaxProduct() {
            var myVariable;
            var prosku = '<?php echo $sku;?>';
            var url = '<?php echo $url;?>';
            jQuery.ajax({
                'async': false,
                'type': "POST",
                'global': false,
                'dataType': 'html',
                'url': url+"amasty_promo/customer/info?ajax=productView&account=32509"+'&sku='+prosku,
                'success': function (data) {
                    myVariable = data;
                }
            });
            return myVariable;
        }
        var product = ajaxProduct();
        jQuery('.productView').html(product);
    </script>
    <script type="text/javascript">
        var sidecar = sidecar || {};
        sidecar.product_info = {
        group_id: '<?php echo $sku;?>'
        };
    </script>

<?php } else if($this->getRequest()->getFullActionName() == 'checkout_cart_index') {

    $om =   \Magento\Framework\App\ObjectManager::getInstance();
    $cartData = $om->create('Magento\Checkout\Model\Cart')->getQuote()->getAllVisibleItems();
    $cartDataCount = count( $cartData );
    $viewBasket = '';
    $i = 1;
    foreach($cartData as $item) {
        $viewBasket .= '{ id: "'.$item->getSku().'", price: '.$item->getPrice().' , quantity: '.$item->getQty().' }';
        if($i < $cartDataCount)
            $viewBasket .= ', ';

        $i++;
    }
?>
    <div class='checkoutCartView'></div>

    <script type="text/javascript">
        function ajaxCheckout() {
            var myVariable;
            var proViewBasket = '<?php echo $viewBasket;?>';
            var url = '<?php echo $url;?>';
            jQuery.ajax({
                'async': false,
                'type': "POST",
                'global': false,
                'dataType': 'html',
                'url': url+"amasty_promo/customer/info?ajax=checkoutCartView&account=32509"+'&viewBasket='+proViewBasket,
                'success': function (data) {
                    myVariable = data;
                }
            });
            return myVariable;
        }
        var checkout = ajaxCheckout();
        jQuery('.checkoutCartView').html(checkout);
    </script>
<?php } ?>

<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3oCObp765Yn9utNHnZR68fdYZbFWf9cL";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->

<script>
jQuery(document).ready(function() {
	jQuery(".qty-inc").unbind('click').click(function(){
        if(jQuery(this).parent().parent().children(".control").children("input.input-text.qty").is(':enabled')){
            jQuery(this).parent().parent().children(".control").children("input.input-text.qty").val((+jQuery(this).parent().parent().children(".control").children("input.input-text.qty").val() + 1) || 0);
            jQuery(this).parent().parent().children(".control").children("input.input-text.qty").trigger('change');
            jQuery(this).focus();
        }
    });
    jQuery(".qty-dec").unbind('click').click(function(){
        if(jQuery(this).parent().parent().children(".control").children("input.input-text.qty").is(':enabled')){
            jQuery(this).parent().parent().children(".control").children("input.input-text.qty").val((jQuery(this).parent().parent().children(".control").children("input.input-text.qty").val() - 1 > 0) ? (jQuery(this).parent().parent().children(".control").children("input.input-text.qty").val() - 1) : 0);
            jQuery(this).parent().parent().children(".control").children("input.input-text.qty").trigger('change');
            jQuery(this).focus();
        }
    });
});
</script>

