<style type="text/css">
    span.custom-required{color: #ff0000;}
    h1 {
        font-size: 26px;
        font-weight: 600;
        margin: 0 0 15px;
    }
    .r9-contact-form {
    border-radius: 10px;
    border-top: 3px solid #0088cc;
    padding-top: 15px;
}
    .r9-contact-form input,.r9-contact-form select {
    margin-bottom: 15px;
    margin-top: 6px;
    border-radius:3px;
    height:35px;
	}
	.sub-btn {
    clear: both;
    padding-left: 20px;
    padding-top: 20px;
}
.r9-contact-form .check-box {clear:both;padding-left:15px}
.r9-contact-form .check-box input {margin:0 0 0 5px;height:auto;}

.r9-contact-form div.mage-error[generated] {position:inherit;top:-12px;}
	.quote-description{display: block;clear: both;margin-top: 10px}
	.col-md-12.custom-field {padding-left: 0;padding-right: 0;}
    .col-md-12.custom-field .form-group {margin-bottom: 0;}
	
</style>
<?php
/**
 * @var $block \Kensium\Quote\Block\Quote
 */
$storeName = $block->getCurrentStoreName();
$storeId = $block->getCurrentStoreId();
?>
    <h1 style="text-align: left;"><?php /* @escapeNotVerified */ echo __('Request a Quote')?></h1>
    <p><?php /* @escapeNotVerified */ echo __('Please fill out the following form.')?></p>
    <p><span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('Indicates a required field.')?></p>
    <form action="<?php echo $block->getAction(); ?>" id="contact_us" method="post" name="myform">
    
<div class="r9-contact-form">
    
 <fieldset class="fieldset">

<!-- Text input-->
<div class="form-group">
    
<input type="hidden" name="store_id" value="<?php  echo $storeId; ?>" />
</div>

<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('First Name:')?>
  <input id="fname" name="fname" class="input-text required-entry" data-validate="{required:true}" title="First Name" type="text" />
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('Last Name:')?>
  <input id="lname" name="lname" class="input-text required-entry" data-validate="{required:true}" title="Last Name" type="text" />
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
 
  <div class="col-md-6">
  <?php /* @escapeNotVerified */ echo __('Business/Organization Name')?>
  <input id="bname" name="bname"  title="bname" type="text" />
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('Address')?>
  <input id="address" name="address" class="input-text required-entry" data-validate="{required:true}" title="address" type="text" />
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('City')?>
  <input id="city" name="city" class="input-text required-entry" data-validate="{required:true}" title="city" type="text" />
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('State/Province')?>
  <input id="state" name="state" class="input-text required-entry" data-validate="{required:true}" title="state" type="text" />
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('ZIP')?>
  <input id="zip" name="zip" class="input-text required-entry" data-validate="{required:true, 'validate-zip-us':true}" title="zip" type="text" />
    
  </div>
</div>
           
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('Country:')?>
  <input id="country" name="country" class="input-text" data-validate="{required:true}" title="country" type="text" />
    
  </div>
</div>
<!-- Text input-->
<div class="col-md-12 custom-field">
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('Phone Number:')?>
  <input id="phone" name="phone" class="input-text required-entry" data-validate="{required:true, 'validate-phoneStrict':true}" title="Phone" type="text" />
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <?php /* @escapeNotVerified */ echo __('FAX:')?>
  <input id="fax" name="fax" class="input-text"  title="fax" type="text" />
    
  </div>
</div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-6">
  <span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('Email address:')?>
  <input id="email" name="email" class="input-text required-entry validate-email" data-validate="{required:true, 'validate-email':true}" type="email" />
    
  </div>
</div>
           
    <p class="quote-description"><?php /* @escapeNotVerified */ echo __('To add a product to your quote, please complete the fields below and click submit.')?>
            <span style="color: #F00; font-weight: bold;"><?php /* @escapeNotVerified */ echo __('PLEASE NOTE:')?> </span>
            <?php /* @escapeNotVerified */ echo __('If an Item# ends in "-P" then you will need to specify the color/size/style of this item in the Description field. Omitting this information may delay processing of your quote.')?>
        </p>
           <?php for($i = 1;$i<=10;$i++){?>
		
<!-- Text input-->
<div class="form-group">
  <div class="col-md-3">
  <?php /* @escapeNotVerified */ echo __('Quantity')?><?php echo $i;?>
  <input class="formtext input-xsmall" type="number"  value="" name="<?php echo 'qty'.$i;?>">  
  </div>
</div>

<div class="form-group">
  <div class="col-md-3">
  <?php /* @escapeNotVerified */ echo __('Item')?><?php echo $i;?>
  <input class="formtex input-small" type="text"  value="" name="<?php echo 'item'.$i;?>">
  </div>
</div>

<div class="form-group">
  <div class="col-md-6">
  <?php /* @escapeNotVerified */ echo __('Description')?><?php echo $i;?>
   <input class="formtext input-large" type="text"  value="" name="<?php echo 'description'.$i;?>">
  </div>
</div>	
    
<?php }?>
</fieldset> 
<!-- Text input-->
<div class="form-group">
  <div class="col-md-6">
  <?php echo $block->getChildHtml('catcaptcha');?>
    
  </div>
</div>
<!-- Text input-->
<div class="sub-btn">
   <button type="submit" class="action primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
  <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
    
  </div>

</div>          
</form>
<p class="quote-desc">If this online form will not accommodate your quote request, or if you prefer to use a written form, you may download our <br> <a href="<?php echo $block->getUrl().'pub/media/RAM-quote-form-2014.pdf';?>" target="_new" style="text-decoration: underline;">Request for Quote pdf form </a> and fax it to Ray Allen Manufacturing. Our contact information, and written instructions, are included on the form.</p>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){

        var dataForm = $('#contact_us');
        var ignore = '';
        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

    });
</script>
