<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <span data-ui-id="page-title-wrapper" class="base">Ray Allen Order Tracking</span>    </h1>
</div>
<div>
  <strong>For questions please contact Ray Allen Customer Service:</strong><br>
  <br>
  (800) 444-0404 or (719) 380-0404<br>
  Monday - Friday<br>
  9am-6pm, Eastern Time<br>
  <!-- 9am-7pm, Eastern Time<br>-->
  Email:&nbsp;<a href="mailto:sales@rayallen.com">sales@rayallen.com</a><br>
</div>
<form class="form form-orders-search" id="oar-widget-orders-and-returns-form" data-mage-init='{"ordersReturns":{}, "validation":{}}' action="<?php /* @escapeNotVerified */ echo $block->getActionUrl() ?>"
      method="post" name="guest_post">
    <fieldset class="fieldset">
      <!--  <legend class="admin__legend"><span><?php /* @escapeNotVerified */ echo __('Order Information') ?></span></legend>-->
        <br>

        <div class="field id required">
            <label class="label" for="oar-order-id"><span><?php /* @escapeNotVerified */ echo __('Order ID') ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar-order-id" name="oar_order_id"
                       data-validate="{required:true}"/>
            </div>
        </div>
       <!-- <div class="field lastname required">
            <label class="label" for="oar-billing-lastname"><span><?php /* @escapeNotVerified */ echo __('Billing Last Name') ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar-billing-lastname" name="oar_billing_lastname"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field find required">
            <label class="label" for="quick-search-type-id"><span><?php /* @escapeNotVerified */ echo __('Find Order By') ?></span></label>

            <div class="control">
                <select name="oar_type" id="quick-search-type-id" class="select">
                    <option value="email"><?php /* @escapeNotVerified */ echo __('Email'); ?></option>
                    <option value="zip"><?php /* @escapeNotVerified */ echo __('ZIP Code'); ?></option>
                </select>
            </div>
        </div>
        <div id="oar-email" class="field email required">
            <label class="label" for="oar_email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>

            <div class="control">
                <input type="email" class="input-text" id="oar_email" name="oar_email"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>-->
        <div id="oar-zip" class="field zip required">
            <label class="label" for="oar_zip"><span><?php /* @escapeNotVerified */ echo __('Billing ZIP Code') ?></span></label>

            <div class="control">
                <input type="text" class="input-text" id="oar_zip" name="oar_zip" data-validate="{required:true}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Continue') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Continue') ?></span>
            </button>
        </div>
    </div>
</form>
