<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<?php
$logData = $block->getLog();
?>
<?php $style = 'style="float:left;padding:5px;width:25%;text-align:left;padding-left:15px"';?>
<div style="background-image: linear-gradient(hsla(207, 10%, 35%, 0.97), hsla(207, 5%, 25%, 0.92));color:#fff;line-height: 20px;padding:10px"><h3>Log Data:</h3></div>

<table style="border: 1px solid #d6d6d6;width:100%" cellspacing="2" class="log-info table">
    <col width="100%" />
    <col />
    <tbody>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Aggregated Information</b></td>
        <td width='75%' <?php echo $style; ?>></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Sync Date:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData['created_at']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Accumatica Attribute Code:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData['acumatica_attribute_code']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Description:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData['description']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Sync Direction:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData['sync_direction']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Message Type:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData['message_type']; ?></td>
    </tr>


    </tbody>
</table><br>

<?php
$logDetail = $block->getLogDetails();
?>


<?php if (isset($logDetail[0]['long_message']) && $logDetail[0]['long_message'] != '') { ?>
    <br>
   <div style="background-image: linear-gradient(hsla(207, 10%, 35%, 0.97), hsla(207, 5%, 25%, 0.92));color:#fff;line-height: 20px;padding:10px"> <h3>Error Trace:</h3></div>
    <table style="border: 1px solid #d6d6d6;width:100%" cellspacing="2" class="log-info table">
        <tr>
            <td width='25%' style="text-align: left;"><b>Error Trace</b></td>
            <td width='75%' style="text-align: left;"> <?php echo $logDetail[0]['long_message']; ?> </td>
        </tr>


    </table>

<?php } ?>
