<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<?php $logDet = $block->getLogDetails();
$scheduleAt = new DateTime($logDet['created_at']);
$diff = $scheduleAt->diff(new DateTime($logDet['finished_at']));
$synduration = $diff->days . ' days , ' . $diff->h . " : " . $diff->i . " : " . $diff->s;
?>

<div>
    <div class="entry-edit">
        <table style="width:100%;background-color:lightgray;" cellspacing="2" class="log-info table">
            <tr>
                <td width='25%' style="text-align: left;"><b>Sync Entity:</b></td>
                <td width='25%' style="text-align: left;"><?php echo $logDet['job_code']; ?></td>
                <td width='25%' style="text-align: left;"><b>Scheduled At :</b></td>
                <td width='25%'
                    style="text-align: left;"><?php $dateExecutedAt = new DateTime($logDet['scheduled_at']);
                    $formatedExecutedAt = $dateExecutedAt->format('M d, Y h:i:s A');
                    echo $formatedExecutedAt; ?></td>
            </tr>

            <tr>
                <td width='25%' style="text-align: left;"><b>Sync Status:</b></td>
                <td width='25%' style="text-align: left;"><?php echo $logDet['status']; ?></td>
                <td width='25%' style="text-align: left;"><b>Executed At :</b></td>
                <td width='25%'
                    style="text-align: left;"><?php $dateExecutedAt = new DateTime($logDet['executed_at']);
                    $formatedExecutedAt = $dateExecutedAt->format('M d, Y h:i:s A');
                    echo $formatedExecutedAt; ?></td>
            </tr>

            <tr>
                <td width='25%' style="text-align: left;"><b>Created At:</b></td>
                <td width='25%'
                    style="text-align: left;"><?php $dateExecutedAt = new DateTime($logDet['created_at']);
                    $formatedExecutedAt = $dateExecutedAt->format('M d, Y h:i:s A');
                    echo $formatedExecutedAt; ?></td>
                <td width='25%' style="text-align: left;"><b>Finished At :</b></td>
                <td width='25%'
                    style="text-align: left;"><?php $dateExecutedAt = new DateTime($logDet['finished_at']);
                    $formatedExecutedAt = $dateExecutedAt->format('M d, Y h:i:s A');
                    echo $formatedExecutedAt; ?></td>
            </tr>

            <tr>
                <td width='25%' style="text-align: left;"><b>Sync Duration:</b></td>
                <td><?php echo $synduration; ?></td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
</div>


<?php
echo $block->getGridHtml();
?>
