<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Category left navigation
 *
 * @var $block \Magento\Catalog\Block\Navigation
 */
?>
<?php echo "test";?>
<?php

$_categories = $block->getCurrentChildCategories();

//$categories = $this->_catalogLayer->getCurrentCategory()->getChildrenCategories();
//print_r($categories);
?>