<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattr
 */
?>
<?php
/** @var $block \Amasty\Orderattr\Block\Checkout\Attributes */
?>

<script type="text/javascript">
    require([
        'uiRegistry'
    ], function(uiRegistry) {
        uiRegistry.set('amastyOrderAttributes', <?= $block->getAttributeCodes() ?>);
    });
</script>
