<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<?php $buttonTitle = __('View and Edit Cart'); ?>
<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php echo $block->getShoppingCartUrl(); ?>" title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php echo __('Shopping Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: cart().summary_count == 0 }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: '(' --><!-- /ko --><!-- ko text: cart().summary_count --><!-- /ko --><!-- ko text: ')' --><!-- /ko -->
            </span>			
            <span class="counter-label">
            <!-- ko if: cart().summary_count <= 1 -->
                <!-- ko i18n: 'item :' --><!-- /ko -->
            <!-- /ko -->
            <!-- ko if: cart().summary_count > 1 -->
                <!-- ko i18n: 'items :' --><!-- /ko -->
            <!-- /ko -->	
			<span data-bind="html: cart().subtotal"></span>		
            </span>	
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
				<!-- ko if: cart().summary_count >= 1 -->
				<div class="min-cart-subtotal">
					<span class="label">
					Cart Subtotal : 
				</span>
				<span data-bind="html: cart().subtotal"></span>
				</div>
				<!-- /ko -->
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>


