<?php

//die(print_r($_REQUEST));
//var_dump($block);

$block->addSKUProductToCart();

//echo "This is the content of the test form here so please ignore this test here";
//$block->messageManager->addSuccess('Yes this is a success message here');
?>
<!--<div id="messages_product_view"><?php $block->sessionGeneric->setData('suc_msg'); ?></div> -->
<script>
    //alert('yes the pop up');
   // window.location.href = "<?php echo $block->urlBase()."quickorder/Quick/Order"; ?>";
</script>