<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>

<?php 
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<?php if ($_additional = $_product->getVideo()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
		<iframe width="420" height="315" src="<?php echo $_product->getVideo(); ?>" frameborder="0" allowfullscreen></iframe>
    </div>
<?php endif;?>
