<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<?php $buttonTitle = __('Email Friend'); ?>
<?php if ($block->canEmailToFriend()): ?>
    <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>" class="action mailto friend"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></a><span>
<?php endif; ?>
