<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>

<?php 
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<?php if ($_additional = $_product->getCompareProducts()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
		<?php echo $_product->getCompareProducts(); ?>
    </div>
<?php endif;?>
