<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<?php $logDet = $block->getLogDetails();
$dateObject = $block->getDateObject();
$scheduleAt =new DateTime($logDet['created_at']); //$dateObject->date('Y-m-d H:i:s', $logDet['created_at']);
$diff = $scheduleAt->diff(new DateTime($logDet['finished_at']));
$synduration = $diff->days . ' days , ' . $diff->h . " : " . $diff->i . " : " . $diff->s;

?>
<?php if(isset($_SERVER["HTTP_REFERER"])) { ?>
    <input type="button" class="action-default scalable action-secondary" value="Back" onclick="window.location.href='<?php echo $block->getBackUrl(); ?>'" /> <br>
<?php }?><br>
<?php $style = 'style="float:left;padding:5px;width:25%;text-align:left;padding-left:15px"';?>
<div class="entry-edit">
    <div class="entry-edit">
        <div class="example-responsive-block">
            <h4 class="" style="background-image: linear-gradient(hsla(207, 10%, 35%, 0.97), hsla(207, 5%, 25%, 0.92));color:#fff;line-height: 20px;padding:10px"><?php echo'Log Data'; ?></h4>
        </div>
        <div id="log_details_fieldset" class="log-details">
        <table style="border: 1px solid #d6d6d6;" cellspacing="2" class="log-info table">
            <col width="100%" />
            <col />
            <tbody>
            <tr>
                <td width='25%' <?php echo $style; ?>><b>Sync Entity:</b></td>
                <td width='25%' <?php echo $style; ?>><?php echo $logDet['job_code']; ?></td>
                <td width='25%'<?php echo $style; ?>><b>Scheduled At :</b></td>
                <td width='25%'
                    <?php echo $style; ?>><?php echo $dateObject->date($logDet['scheduled_at'],null,true)->format('M d, Y h:i:s A');
                    ?></td>
            </tr>

            <tr>
                <td width='25%' <?php echo $style; ?>><b>Sync Status:</b></td>
                <td width='25%' <?php echo $style; ?>><?php echo $logDet['status']; ?></td>
                <td width='25%' <?php echo $style; ?>><b>Executed At :</b></td>
                <td width='25%'
                    <?php echo $style; ?>><?php echo $dateObject->date($logDet['executed_at'],null,true)->format('M d, Y h:i:s A');

                    ?></td>
            </tr>

            <tr>
                <td width='25%' <?php echo $style; ?>><b>Created At:</b></td>
                <td width='25%'
                    <?php echo $style; ?>><?php echo $dateObject->date($logDet['created_at'],null,true)->format('M d, Y h:i:s A');

                    ?></td>
                <td width='25%' <?php echo $style; ?>><b>Finished At :</b></td>
                <td width='25%'
                    <?php echo $style; ?>><?php  echo $dateObject->date($logDet['finished_at'],null,true)->format('M d, Y h:i:s A');

                    ?></td>
            </tr>

            <tr>
                <td width='25%' <?php echo $style; ?>><b>Sync Duration:</b></td>
                <td <?php echo $style; ?>><?php echo $synduration; ?></td>
                <td></td>
                <td></td>
            </tr>
            </tbody>
        </table>
            </div>
    </div>
</div>


<?php
echo $block->getGridHtml();
?>
