<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<html>
<head>
    <title>Kensium log viewer</title>
    <script  type="text/javascript"  src="<?php echo $data['pubStaticUrl'].'adminhtml/Magento/backend
/en_US/Kensium_Amconnector/js/jquery.min.js';?>"></script>
    <?php if( isset($data['stopSyncUrl'])) { ?>
        <script>
            function stopSync(path) {
                var data = {"path": path};
                $.ajax({
                    type: "GET",
                    url: "<?php echo $data['stopSyncUrl']; ?>",
                    data: data,
                    success: function (data) {
                    }
                });
            }
            $(function () {
                $(".stop-btn").on('click', function () {
                    $(this).hide();
                    $(this).parent().find("#sync-process-img").hide();
                });
            });

        </script>
    <?php } ?>
    <style>
        .stop-btn:hover {
            background: #f77c16 url("<?php echo $data['pubStaticUrl'].'adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/btn_over_bg.gif';?>") repeat-x scroll 0 0;
        }
    </style>
</head>
<body>
<input hidden id="logurl" value="<?php echo $data['ajaxLogUrl']; ?>"/>
<input hidden id="logPath" value="<?php echo $data['logPath']; ?>"/>
<pre id="data">Loading...</pre>
<script  type="text/javascript"  src="<?php echo $data['pubStaticUrl'].'adminhtml/Magento/backend/en_US/Kensium_Amconnector/js/logtail.js';?>"></script>
<form>
    <div id='sync-process-img' style="position: fixed; bottom: -9px; width: 97%; background: #fff; height: 66px; " >
        <div class="process" style="font: 15px arial, helvetica, sans-serif; display: inline-block; vertical-align: middle; padding: 15px 0 0;">Processing</div>
        <div class="processing-img" style="font: 15px arial, helvetica, sans-serif; display: inline-block; vertical-align: middle; padding: 15px 0 0;">
            <div class="processing-img" style="font: 15px arial, helvetica, sans-serif; display: inline-block; vertical-align: middle; padding: 15px 0 0;">
                <img src='<?php echo $data['pubStaticUrl'].'adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/sync-ajax-loader-red.gif';?>' width='72' height='20' style='float:left;padding: 5px 15px 20px 5px;'/>
            </div>
        </div>
    </div>
    <?php  if (isset($data['syncStop']) && $data['syncStop'] == 1) { ?>
        <input type="button" value="Stop Sync" class="stop-btn" id="stop-btn"
               onclick="javascript:stopSync('<?php echo $data['path']; ?>')"   style="
            background: #ffac47 url(<?php echo $data["pubStaticUrl"]."adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/btn_bg.gif";?>) repeat-x scroll 0 100%;
            border-color: #ed6502 #a04300 #a04300 #ed6502;
            border-style: solid;
            border-width: 1px;
            color: #fff;
            cursor: pointer;
            font: bold 13px arial, helvetica, sans-serif;
            padding: 5px 20px 5px;
            text-align: center !important;
            white-space: nowrap;
            position: fixed;
            right: 5px;
            bottom: 2px;"

               onmouseout="
                   this.style.background = '#F56F09 url(<?php echo $data["pubStaticUrl"]."adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/btn_bg.gif";?>) repeat-x scroll 0 0';
                   this.style.borderColor = '#ed6502 #a04300 #a04300 #ed6502';
                   this.style.borderStyle = 'solid';
                   this.style.borderWidth = '1px';
                   this.style.color = '#fff';
                   this.style.cursor= 'pointer';
                   this.style.font = 'bold 13px arial, helvetica, sans-serif';
                   this.style.padding = '5px 20px 5px';
                   this.style.textAlign = 'center !important';
                   this.style.whiteSpace = 'nowrap';
                   this.style.position= 'fixed';
                   this.style.right= '5px';
                   this.style.bottom = '2px';

               "
               onmouseover="this.style.background = '#f77c16 url(<?php echo $data["pubStaticUrl"]."adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/btn_over_bg.gif";?>) repeat-x scroll 0 0 ' "   >
    <?php }?>
</form>

</body>
</html>