<style type="text/css">
    span.custom-required{color: #ff0000;}
    h1 {
        font-size: 26px;
        font-weight: 600;
        margin: 0 0 15px;
    }
    .r9-contact-form {
    border-radius: 10px;
    border-top: 3px solid #0088cc;
    padding-top: 15px;
}
    .r9-contact-form input,.r9-contact-form select {
    margin-bottom: 15px;
    margin-top: 6px;
    border-radius:3px;
    height:35px;
	}
	.sub-btn {
    clear: both;
    padding-left: 20px;
    padding-top: 20px;
}
.r9-contact-form .check-box {clear:both;padding-left:15px;padding-top:10px}
.r9-contact-form .check-box input {margin:0 0 0 5px;height:auto;}

.r9-contact-form div.mage-error[generated] {position:inherit;top:-12px;}
	
	
</style>
<?php
$storeName = $block->getCurrentStoreName();
$storeId = $block->getCurrentStoreId();
?>
<div class="row">
<!--    <h1 itemprop="name" style="margin-bottom: 1em;"><?php /* @escapeNotVerified */ //echo __('Contact J&J Dog Supplies') ?></h1>-->
    <div class="col-md-5">
        <p><?php /* @escapeNotVerified */ echo __('If you have questions, concerns, suggestions or comments, we would like to hear from you. You may provide hard-copy communication by mail or FAX to:')?></p>
        <p><?php /* @escapeNotVerified */ echo __('Gift Certificates can not be used online, please call, fax, or mail your order in.')?></p>
        <span itemtype="http://schema.org/PostalAddress" itemscope="" itemprop="address"><p><strong><?php /* @escapeNotVerified */ echo __('Postal Address:')?></strong><br /><?php /* @escapeNotVerified */ echo __('J&J Dog Supplies')?><span itemprop="streetAddress"><?php /* @escapeNotVerified */ echo __('975 Ford St.')?></span></p>

        <p><span itemprop="addressLocality"><?php /* @escapeNotVerified */ echo __('Colorado Springs ')?></span>, 
        <span itemprop="addressRegion"> <?php /* @escapeNotVerified */ echo __('CO')?></span>
        <span itemprop="postalCode"><?php /* @escapeNotVerified */ echo __('80915')?></span><br />
            <?php /* @escapeNotVerified */ echo __('U.S.A.')?><br />
            <?php /* @escapeNotVerified */ echo __('Fax: 1 (719) 380-9730 (24-hours)')?></p>

        <p><a href="mailto:sales@jjdog.com" class="body"><?php /* @escapeNotVerified */ echo __('sales@jjdog.com')?></a></p>

        <?php /*<p><?php /* @escapeNotVerified  echo __('Or phone us Monday-Friday 9am - 7pm')?><br /> */?>
        <p><?php /* @escapeNotVerified */ echo __('Or phone us Monday-Friday 9am - 6pm, Eastern Time')?><br />
	<?php /* @escapeNotVerified */ echo __('ET: '); ?>
        <span itemprop="telephone"><?php /* @escapeNotVerified */ echo __('(800) 642-2050 or (719) 434-5980')?></span>
            <?php /* @escapeNotVerified */ echo __('Or send us e-mail at:')?> <a href="mailto:sales@jjdog.com" class="body"><?php /* @escapeNotVerified */ echo __('sales@jjdog.com')?></a><br /></p>
           

        <p><?php /* @escapeNotVerified */ echo __('To report technical problems with our web site, e-mail:')?><a href="mailto:sales@jjdog.com" class="body"><?php /* @escapeNotVerified */ echo __('sales@jjdog.com')?></a><br /></p>
   
   </div>

    <div class="col-md-1">  </div>
    <div class="col-md-6">
        <p class="normaltext"><span style="color: #FF0000">*</span> <?php /* @escapeNotVerified */ echo __('Indicates a required field.')?></p>

        <form action="<?php echo $block->getAction(); ?>" id="contact_us" method="post" name="myform">
               <div class="r9-contact-form">
    
       <fieldset class="fieldset">

<!-- Text input-->
       <div class="form-group">
    
        <input type="hidden" name="store_id" value="<?php  echo $storeId; ?>" />
       </div>
       
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('First Name:')?></div>
  <div class="col-md-8"><input id="fname" name="fname" class="input-text required-entry" data-validate="{required:true}" title="First Name" type="text" /></div>
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('Last Name:')?></div>
  <div class="col-md-8"><input id="lname" name="lname" class="input-text required-entry" data-validate="{required:true}" title="Last Name" type="text" /></div>
    
  </div>
</div>
					

<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('Address:')?></div>
  <div class="col-md-8"><input id="address" name="address" class="input-text"  title="Address" type="text" /></div>
    
  </div>
</div> 

<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('City:')?></div>
  <div class="col-md-8"><input id="city" name="city" class="input-text"  title="City" type="text" /></div>
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
 <div class="col-md-4"> <?php /* @escapeNotVerified */ echo __('State:')?></div>
 <div class="col-md-8"> 
 <select name="state" id="state" class="input-text"  title="State">
                     <option value="AL">Alabama</option>
                    <option value="AK">Alaska</option>
                    <option value="AZ">Arizona</option>
                    <option value="AR">Arkansas</option>
                    <option value="CA">California</option>
                    <option value="CO">Colorado</option>
                    <option value="CT">Connecticut</option>
                    <option value="DE">Delaware</option>
                    <option value="DC">District Of Columbia</option>
                    <option value="FL">Florida</option>
                    <option value="GA">Georgia</option>
                    <option value="HI">Hawaii</option>
                    <option value="ID">Idaho</option>
                    <option value="IL">Illinois</option>
                    <option value="IN">Indiana</option>
                    <option value="IA">Iowa</option>
                    <option value="KS">Kansas</option>
                    <option value="KY">Kentucky</option>
                    <option value="LA">Louisiana</option>
                    <option value="ME">Maine</option>
                    <option value="MD">Maryland</option>
                    <option value="MA">Massachusetts</option>
                    <option value="MI">Michigan</option>
                    <option value="MN">Minnesota</option>
                    <option value="MS">Mississippi</option>
                    <option value="MO">Missouri</option>
                    <option value="MT">Montana</option>
                    <option value="NE">Nebraska</option>
                    <option value="NV">Nevada</option>
                    <option value="NH">New Hampshire</option>
                    <option value="NJ">New Jersey</option>
                    <option value="NM">New Mexico</option>
                    <option value="NY">New York</option>
                    <option value="NC">North Carolina</option>
                    <option value="ND">North Dakota</option>
                    <option value="OH">Ohio</option>
                    <option value="OK">Oklahoma</option>
                    <option value="OR">Oregon</option>
                    <option value="PA">Pennsylvania</option>
                    <option value="RI">Rhode Island</option>
                    <option value="SC">South Carolina</option>
                    <option value="SD">South Dakota</option>
                    <option value="TN">Tennessee</option>
                    <option value="TX">Texas</option>
                    <option value="UT">Utah</option>
                    <option value="VT">Vermont</option>
                    <option value="VA">Virginia</option>
                    <option value="WA">Washington</option>
                    <option value="WV">West Virginia</option>
                    <option value="WI">Wisconsin</option>
                    <option value="WY">Wyoming</option>
                </select>
</div>
       </div>
      </div>

<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('Postal Code:')?></div>
  <div class="col-md-8"><input id="zip" name="zip" class="input-text" title="Zip" type="text" /></div>
    </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><span class="custom-required">*</span><?php /* @escapeNotVerified */ echo __('Email address:')?></div>
  <div class="col-md-8"><input id="email" name="email" class="input-text required-entry validate-email" data-validate="{required:true, 'validate-email':true}" type="email" />
    </div>
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('Phone Number:')?></div>
  <div class="col-md-8"><input id="phone" name="phone" class="input-text"  title="Phone" type="text" /></div>
    
  </div>
</div>
<!-- Text input-->    
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('Fax:')?></div>
  <div class="col-md-8"><input id="text" name="fax" class="input-text"  title="Fax" type="text" /></div>
    
  </div>
</div>  
<!-- Text input-->    
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('Website:')?></div>
  <div class="col-md-8"><input id="website" name="website" class="input-text"  title="Website" type="text" /></div>
    
  </div>
</div>       
<!-- Text input-->    
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('Company:')?></div>
  <div class="col-md-8"><input id="company" name="company" class="input-text"  title="company" type="text" /></div>
    
  </div>
</div>       
<!-- Text input-->    
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('Position:')?></div>
  <div class="col-md-8"><input id="position" name="position" class="input-text"  title="position" type="text" /></div>
    
  </div>
</div>       
    <!-- Text input-->    
<div class="form-group">
  
  <div class="col-md-12">
  <div class="col-md-4"><?php /* @escapeNotVerified */ echo __('Comments:')?></div>
  <div class="col-md-8"><textarea name="comments" rows="7" cols="25" class="formtext input-large"></textarea></div>
    
  </div>
</div>       
<!-- Text input-->
<div class="check-box">
 <input id="hear" name="opt_out" value="y" class="input-text"  type="checkbox" />
 <?php /* @escapeNotVerified */ echo __('Please do NOT add me to the J&J Dog Supplies mailing list.')?>
</div>
</fieldset>

<!-- Text input-->
<div class="form-group">
  
  <div class="col-md-12">
  <?php echo $block->getChildHtml('catcaptcha');?>
  
    
  </div>
</div>
<!-- Text input-->
<div class="sub-btn">
   <button type="submit" class="action primary" data-action="save-address" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
  <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
    
  </div>
</div>
</form>
</div>
</div>

<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){

        var dataForm = $('#contact_us');
        var ignore = '';
        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

    });
</script>
