<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<script type="text/javascript">
    require([
        "jquery",
        "Kensium_Amconnector/js/jquery.colorbox-min"
    ], function (jQuery) {

        jQuery(document).ready(function () {
            jQuery(".amconnectoraction").change(function () {
                  var logviewurl = jQuery(this).parents("tr").find(".logUrl").val();
                  var filterurl = jQuery(this).parents("tr").find(".filterUrl").val();
                  var baseurl = jQuery(this).parents("tr").find(".baseurl").val();
                  var synctitle = jQuery(this).parents("tr").find(".title").val();
                  var rowId = jQuery(this).parents("tr").find(".rowId").val();
                  var url = jQuery(this).parents("tr").find(".url").val();
                  var licenseType = jQuery(this).parents("tr").find(".licenseType").val();
                if (this.value == 1) {
                    jQuery.colorbox({
                        html: "",
                        rel: 'group3',
                        href: logviewurl,
                        iframe: true,
                        innerWidth: "50%",
                        innerHeight: "50%",
                        title: "<div style  = 'float:left;width:100%;background-size:100% 100%;height:50px;background-image:url(" + baseurl + "adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/header_bg.gif);' > <span style='height: 36px; width: 35px; padding: 2px; text-align: center; margin: 6px -5px 0px 10px; float: left; background:#fff url(" + baseurl + "adminhtml/Magento/backend/en_US/Kensium_Amconnector/images/amconnector/amconnector_medium.png) no-repeat 2px 2px; border-radius: 20px;' ></span>  <span style = 'float:left;font-size:20px;font-weight:bold;color:white;padding: 14px; ' >Acumatica - " + synctitle+ " <span style='color:#F48220'>" + licenseType + "</span></span> </div>",
                        onClosed: function () {
                            location.reload(true);
                        }
                    });
                    jQuery.ajax({
                        url: url,
                        method: "GET",
                        data: {
                            id: rowId
                        },
                        success: function (response) {
                        },
                        fail: function () {
                        }
                    });
                } else if (this.value == 2) {
                    setLocation(filterurl);
                }

            });

        });
    });

</script>
<?php echo $block->getGridHtml(); ?>
