<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<?php
$logData = $block->getLog();
$dateObject = $block->getDateObject();

?>
<?php $style = 'style="float:left;padding:5px;width:25%;text-align:left;padding-left:15px"';?>
<?php if(isset($_SERVER["HTTP_REFERER"])) { ?>
    <input type="button" class="action-default scalable action-secondary" value="Back" onclick="window.location.href='<?php echo $_SERVER["HTTP_REFERER"]; ?>'" /> <br>
<?php }?><br>
<div class="example-responsive-block">
    <h4 class="" style="background-image: linear-gradient(hsla(207, 10%, 35%, 0.97), hsla(207, 5%, 25%, 0.92));color:#fff;line-height: 20px;padding:10px"><?php echo'Log Data'; ?></h4>
</div>
<table style="border: 1px solid #d6d6d6;width:100%" cellspacing="2" class="log-info table">
    <col width="100%" />
    <col />
    <tbody>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Aggregated Information</b></td>
        <td width='75%' <?php echo $style; ?>></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Sync Date:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $dateObject->date($logData[0]['created_at'],null,true)->format('M d, Y h:i:s A');?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Order Id:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['order_id']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Accumatica Order Id :</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['acumatica_order_id']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Description : </b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['description']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Action:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['action']; ?></td>
    </tr>
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Sync Action:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['sync_action']; ?></td>
    </tr>
   
    <tr>
        <td width='25%' <?php echo $style; ?>><b>Message Type:</b></td>
        <td width='75%' <?php echo $style; ?>><?php echo $logData[0]['message_type']; ?></td>
    </tr>
    </tbody>
</table><br>
<div class="example-responsive-block">
    <h4 class="" style="background-image: linear-gradient(hsla(207, 10%, 35%, 0.97), hsla(207, 5%, 25%, 0.92));color:#fff;line-height: 20px;padding:10px"><?php echo'Synced Data'; ?></h4>
</div>
<?php
$logDetail = $block->getLogDetails();
?>


<?php if ( isset($logDetail[0]['long_message']) && $logDetail[0]['long_message'] != '') { ?>
    <br>
    <h3>Error Trace:</h3>
    <table style="background-color:lightgrey;width:100%;">
        <tr>
            <td width='25%' <?php echo $style; ?>><b>Error Trace</b></td>
            <td width='75%' <?php echo $style; ?>> <?php echo $logDetail[0]['long_message']; ?> </td>
        </tr>


    </table>

<?php } ?>
