<?php
    $_category_desc = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category/category_description');
?>
<?php if ($_category_desc == "main_column" && $_description = $block->getCurrentCategory()->getDescription()): ?>
    <div class="category-description">
        <?php echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') ?>
    </div>
	<div class="category-clear"></div>
<?php endif; ?>

<?php 
$catId = $block->getCurrentCategory()->getId();
$categoryChildList = $this->helper('Smartwave\Porto\Helper\Data')->getInfo($catId);
if(count($categoryChildList) > 0 ) {
?>

<div class="products grid columns4 products-grid category-grid">
	<ol class="products list items product-items">
	<?php foreach($categoryChildList as $childCategory) { ?>
		<li class="item product product-item">                
			<div data-container="product-grid" class="product-item-info">
				<div class="product photo product-item-photo">
				<a tabindex="-1" href="<?php echo $childCategory['url']; ?>">
<?php if($childCategory['image']) { ?>
				<img alt="<?php echo $childCategory['name']; ?>" src="<?php echo $childCategory['image']; ?>" title="<?php echo $childCategory['name']; ?>" class="product-image-photo default_image" />
<?php } else { ?>
	<img alt="<?php echo $childCategory['name']; ?>" src="<?php echo $this->getBaseUrl().'pub/static/frontend/Smartwave/porto/en_US/Magento_Catalog/images/product/placeholder/image.jpg'; ?>" title="<?php echo $childCategory['name']; ?>" class="product-image-photo default_image" />
<?php } ?>
				</a>
				</div>
				<div class="product details product-item-details">
					<strong class="product name product-item-name">
						<a href="<?php echo $childCategory['url']; ?>" title="<?php echo $childCategory['name']; ?>" class="product-item-link"><?php echo $childCategory['name']; ?></a>
					</strong>
				</div>
			</div>
		</li>
	<?php } ?>
	</ol>
</div>
<?php } ?>

