<?php
/**
 * @category   Amconnector
 * @package    Kensium_Amconnector
 * @copyright  Copyright (c) 2016 Kensium Solution Pvt.Ltd. (http://www.kensiumsolutions.com/)
 */
?>
<?php echo $block->getGridHtml(); ?>
<script>
    function changeValue(url, attribute, coulmnAttr, value, entityTypeId) {
        var url = url + '?attribute=' + attribute + '&entityTypeId=' + entityTypeId + '&attributeValue=' + value + '&coulmnAttr=' + coulmnAttr;
        new Ajax.Request(url, {
            method: 'get',
            asynchronous: false
        });

    }
</script>
